### PR TITLE
Add back UR5-RG2 robot from PR#1

### PR DESCRIPTION
**Pull request by yycho0108**
## Description
PR#1 was closed due to inadvertent merge into main from the source branch.
During the process, the robot URDF file in `examples/urdf` were omitted.
This PR adds the robot back in, so that `arm_motion_UR5.py` is functional again.

## Demonstration

```
# In my case, I use the submodule from `igibson`
$ MOTION_LIB_PATH=../../iGibson/igibson/external/motion python3 arm_motion_UR5.py
```
output

## Changelog
* add `ur5_rg2.urdf`

### CODE REVIEW

**Comment by yycho0108** [comment]
@SNURO

**Comment by SNURO** [comment]
Tried to execute arm_motion_UR5.py and gave me this error. Does it work well on your computer?

Traceback (most recent call last):
  File "examples/arm_motion_UR5.py", line 268, in <module>
    main()
  File "examples/arm_motion_UR5.py", line 142, in main
    robot = UR5RG2(bc, (0, 0, 0), (0, 0, 0, 1))
  File "/home/ro/lab/imm-pybullet-util/examples/robot.py", line 12, in __init__
    self.robot_id: int = bc.loadURDF('./urdf/ur5_rg2.urdf', pos, orn,
pybullet.error: Cannot load URDF file.

**Comment by yycho0108** [comment]
> Tried to execute arm_motion_UR5.py and gave me this error. Does it work well on your computer?
> 
> Traceback (most recent call last): File "examples/arm_motion_UR5.py", line 268, in main() File "examples/arm_motion_UR5.py", line 142, in main robot = UR5RG2(bc, (0, 0, 0), (0, 0, 0, 1)) File "/home/ro/lab/imm-pybullet-util/examples/robot.py", line 12, in **init** self.robot_id: int = bc.loadURDF('./urdf/ur5_rg2.urdf', pos, orn, pybullet.error: Cannot load URDF file.

I think I know what the issue is. Because of the relative path specification, it needs to be run from the `examples/` directory.
@SNURO Can you try that and see if it works? If it does, I'll add that to the documentation.

**Comment by SNURO** [comment]
It works correctly.

**Review by SNURO — APPROVED** [review]

**Pull request merged**
